"""
Title: Ghost knight
Creators: Prem and Liam
Description:A knight killing the undead
"""
#sprite
knight = sprites.create(img("""
    ........................
    .......fff..............
    ....fffff1f.............
    ..ff1111111ff...........
    .ff111111111ff..........
    .f11111111111f..........
    .f1111fffffff1f.........
    ff555111111f15f.........
    ff111111111f11f.....cc..
    f1111111111f11f...ccdc..
    .f111111111f1f..ccddcc..
    ..f1fffffffffffcdddc....
    ...f1111111ffddcdcc.....
    ...f111111f11ddccc......
    ...ffffffffffff.........
    ...fff...ff.............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
"""))
#sprite controls
controller.player1.move_sprite(knight)
def on_jump ():
    knight.vy = -50
controller.A.on_event(ControllerButtonEvent.PRESSED, on_jump)
